# Generated by Django 5.1.3 on 2024-11-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RealEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("price", models.PositiveIntegerField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "apartment"),
                            ("house", "house"),
                            ("land", "land"),
                        ],
                        default="house",
                        max_length=200,
                    ),
                ),
                ("number_of_bedrooms", models.PositiveIntegerField()),
                ("square_footage", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=200)),
                (
                    "property_image",
                    models.ImageField(null=True, upload_to="land_images"),
                ),
                ("contact_details", models.CharField(max_length=200)),
            ],
        ),
    ]
